name: Apply Formatting

on:
  push:
    branches: [master]
    paths:
      - '.github/workflows/formatting.yml'
      - '**/*.cpp'
      - '**/*.hpp'
  workflow_dispatch:

jobs:
  clang-format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run clang-format
        run: find -type f \( -name *.hpp -o -name *.cpp \) | xargs clang-format-16 -style=file -i

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: apply formatting
